// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-e11NnTsNeeVR04rJs_K187MPvwMBm4',
    appId: '1:686707153698:web:dfc04debe293e2f9d3e37b',
    messagingSenderId: '686707153698',
    projectId: 'sendpacket-c6252',
    authDomain: 'sendpacket-c6252.firebaseapp.com',
    storageBucket: 'sendpacket-c6252.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKv7GLL96vTj5rzhA1pJRvwLJowQGVTfA',
    appId: '1:686707153698:android:f3b2620bf49dce4bd3e37b',
    messagingSenderId: '686707153698',
    projectId: 'sendpacket-c6252',
    storageBucket: 'sendpacket-c6252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGJyyOMFgelTiKRKsH07VZ1FwR3GV_nA0',
    appId: '1:686707153698:ios:8b6aeba48eb456e9d3e37b',
    messagingSenderId: '686707153698',
    projectId: 'sendpacket-c6252',
    storageBucket: 'sendpacket-c6252.appspot.com',
    androidClientId: '686707153698-40ic40ogsd7ijtfv3st11a2per6cqvkm.apps.googleusercontent.com',
    iosClientId: '686707153698-64dnc6habi1imoci1sf4qivce1t5o3br.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendPacket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGJyyOMFgelTiKRKsH07VZ1FwR3GV_nA0',
    appId: '1:686707153698:ios:b72a92ef441e9833d3e37b',
    messagingSenderId: '686707153698',
    projectId: 'sendpacket-c6252',
    storageBucket: 'sendpacket-c6252.appspot.com',
    androidClientId: '686707153698-40ic40ogsd7ijtfv3st11a2per6cqvkm.apps.googleusercontent.com',
    iosClientId: '686707153698-bvtsf977qtq0tef1jliikcidq1krp9uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sendPacket.RunnerTests',
  );
}
